services:
  - type: web
    name: rendercv-worker
    env: docker
    rootDir: services/rendercv-worker
    plan: free         # or standard
    envVars:
      - key: RENDER_WORKER_AUTH
        sync: false    # you’ll fill this in the dashboard after deploy
